export const COLORS = {
  PRIMARY: '#117EFF',
  SECONDARY: '#00E1FF',
  TERTIARY: '#1A1731',
  QUATERNARY: '#E4E6F1',
  
  ICON_BLUE: '#3FA8F4',
  ICON_ORANGE: '#EBBD3E',
  ICON_PINK: '#D190DD',
  ICON_GRAY: '#9FABD5',
  ICON_GREEN: '#35C667',
  ICON_KHAKI: '#C1CA4F',

  NEUTRAL: '#EBEEF6',
  WHITE: '#ffffff'
};
