import type { NextPage } from 'next';
import Head from 'next/head'
import Analytics from 'src/screens/Analytics';

const AnalyticsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Better Journeys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Analytics />
    </>
  )
}

export default AnalyticsPage;