import type { NextPage } from 'next';
import Head from 'next/head'
import Clients from 'src/screens/Clients';

const ClientsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Better Journeys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Clients />
    </>
  )
}

export default ClientsPage;