import type { NextPage } from 'next';
import Head from 'next/head'
import Help from 'src/screens/Help';

const HelpPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Better Journeys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Help />
    </>
  )
}

export default HelpPage;