import type { NextPage } from 'next';
import Head from 'next/head'
import Journey from 'src/screens/Journey';

const JourneyPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Better Journeys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Journey />
    </>
  )
}

export default JourneyPage;